# If this is enabled, the management task loading and prioritizing the file form of the portals will be utilized.
management-task: true
# If this is enabled, when the player is teleport they will keep their current Yaw and Pitch.
keep-teleport-head-axis: false
# If this option is enabled, velocity will continue through portal transfers for player and all other entities.
maintain-vehicle-velocity: true
# If this option is enabled, entity (NOT a vehicle) velocity will continue through portal.
# (NOTE: This can kill the entity via fall damage under certain circumstances).
maintain-entity-velocity: true
# If this is enabled, all players will be able to use all portals.
bypass-portal-permissions: true
# If this is enabled, the player can teleport through portals with vehicles, such as Horses and Boats.
vehicle-teleportation: true
# IF this is enabled, portal usage for creative mode players will be blocked entirely.
block-creative-portal-entrance: false

# Adding a world and a location to this list will cause all nether portals in the world to send the player to the specified location.
# Format: <world portal must be in>:<world of to location>,<x>,<y>,<z>,<yaw>,<pitch>
nether-portal-locations:
  - "example_world:world,0,80,0,0,0"
  - "example_world_the_nether:world,0,80,0,0,0"

# Adding a world and a location to this list will cause all end portals in the world to send the player to the specified location.
# Format: <world portal must be in>:<world of to location>,<x>,<y>,<z>,<yaw>,<pitch>
end-portal-locations:
  - "example_world:world,0,80,0,0,0"
  - "example_world_the_end:world,0,80,0,0,0"

# The creatures in the list below will be blocked from spawning inside portal regions.
creature-spawning-blacklist:
  - "PUFFERFISH"
  - "TROPICAL_FISH"
  - "DOLPHIN"

# These define how titles are sent and their durations.
# (Note: Effects both sub-titles and normal titles.)
titles:
  fade-in: 0
  fade-out: 0
  display-time: 5

# Should players have a cooldown for portal usage?
use-portal-cooldown: true
# If this option is enabled, players who join the server will automatically be placed on portal cooldown
# and thrown out of the portal region (if within a portal region).
join-protection: true
# This is the duration of the join protection cooldown.
join-protection-cooldown: 5
# How long should the player have to wait in between portal usages in seconds?
portal-cooldown-duration: 5
# This is the force/multiplier of the portal throw back feature (Set to -1 or lower to disable).
throw-velocity: 1.35
# This is the delay before portal commands are initiated (20 ticks = 1 second).
command-tick-delay: 5

# This allows dropped/spawned items to transfer through portals.
item-transfer: true
# This is how long before the item that was dropped or spawned has its location checked for teleportation.
item-teleport-delay: 2

# This is the sound that is played when the player teleports.
# You may need to change this based on your minecraft version.
teleport-sound: "ENTITY_GHAST_SHOOT"
# This is the effect that is used for your teleportation visual.
# You can find a complete particle list here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
teleport-visual-effect: "CLOUD"

# This is the effect that is used for your selection visual.
# You can find a complete particle list here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
selection-visual-effect: "REDSTONE"
# This is how long the visual will appear on screen.
selection-visual-duration: 10

# This is the effect that is used for your region visual.
# You can find a complete particle list here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
region-visual-effect: "REDSTONE"
# This is how long the visual will appear on screen.
region-visual-duration: 20